### ISSUE TITLE
Issue Running

### ISSUE THREAD

**Issue by Flipsutter** [tishige/CallFlowVisualizer#4]
C:\Users\flips\Downloads\CallFlowVisualizer-Windows-1.6.3\CallFlowVisualizer-Windows-1.6.3>CallFlowVisualizer.exe c:\tem
p\testrichard.json
Mode : GenesysCloud started.

Creating CSV file for GenesysCloud
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CallFlowVisualizer.CollectGCValuesFromJSON.CollectNode(String jsonPath) in C:\Users\tishige\source\repos\tishige\CallFlowVisualizer\CollectGCValuesFromJSON.cs:line 30
   at CallFlowVisualizer.GcJSONtoCSV.gcJsonToCSV(List`1 filePathList, Options opt) in C:\Users\tishige\source\repos\tishige\CallFlowVisualizer\GcJSONtoCSV.cs:line 52
   at CallFlowVisualizer.Program.Main(String[] args) in C:\Users\tishige\source\repos\tishige\CallFlowVisualizer\Program.cs:line 214

**Comment by tishige** [comment]
Hi
Apologies for the late reply.
Can you provide the JSON file of the architect where you encountered the issue so that I can reproduce?
If that's okay, please send me DM request on the Genesys community site.

https://community.genesys.com/discussion/creates-flowcharts-of-genesys-cloud-or-pureconnect-interaction-flow
Ishi

**Comment by tishige** [comment]
Hi
Try v1.8.1
